language: python
matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=flake8
    - python: "2.6"
      env: TOX_ENV=py26
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "3.4"
      env: TOX_ENV=py34
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "pypy"
      env: TOX_ENV=pypy
install:
  - pip install tox
  - if [[ $TOX_ENV == py27 ]] || [[ $TOX_ENV == py36 ]]; then
      pip install coveralls;
    fi
script:
  - tox -e $TOX_ENV
after_success:
  - if [[ $TOX_ENV == py27 ]] || [[ $TOX_ENV == py36 ]]; then
      coveralls;
    fi
