language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=flake8
    - python: "2.6"
      env: TOX_ENV=26
    - python: "2.7"
      env: TOX_ENV=27
    - python: "3.3"
      env: TOX_ENV=33
    - python: "3.4"
      env: TOX_ENV=34
    - python: "3.5"
      env: TOX_ENV=35
    - python: "3.6"
      env: TOX_ENV=36
    - python: "pypy"
      env: TOX_ENV=pypy
install:
  - pip install tox
  - pip install python-coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
